### ISSUE TITLE
This tool will no longer work.  Use subdavis/kobo-book-downloader instead

### ISSUE THREAD

**Issue by subdavis** [TnS-hun/kobo-book-downloader#18]
Several changes at kobo have made this tool unusable. My updated version is actively maintained and has several new features.

https://github.com/subdavis/kobo-book-downloader

Please don't reply to this issue, open issues at https://github.com/subdavis/kobo-book-downloader/issues instead.

**Comment by TnS-hun** [comment]
The program has been updated, and supports the hCaptcha protection on the login page.
