### ISSUE TITLE
ERROR: Capcha mecanism - 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by tioui** [TnS-hun/kobo-book-downloader#19]
Hi, I try to connect to the kobo-book-downloader to Kobo API using the new Capcha mecanism. It seems to found everything it need to connect, but when actually opening the API, it receive a 403 Client Error. I have attached the log file (without my credential of course) with the "--verbose" option

Thanks,
[kobo_error.log](https://github.com/TnS-hun/kobo-book-downloader/files/8532219/kobo_error.log)

**Comment by TnS-hun** [comment]
It should be working again.

**Comment by subdavis** [comment]
@TnS-hun could I ask how you're solving these?  I really appreciate the assistance.

When looking at the auth flow in chrome inspector, the old URL that doesn't work in our apps works just fine.

![Screenshot from 2022-04-24 21-24-16](https://user-images.githubusercontent.com/4214172/165006174-a8376cb1-ab5f-4dd0-93a3-a40b69ce72de.png)

**Comment by TnS-hun** [comment]
I am using the [Genymotion](https://www.genymotion.com/) Android emulator to run the Kobo app, then inspect the traffic that it makes with [HTTP Toolkit](https://httptoolkit.tech/).
