### ISSUE TITLE
ERROR: Can't find the workflow ID in the login form. The page format might have changed.

### ISSUE THREAD

**Issue by dingo35** [TnS-hun/kobo-book-downloader#20]
Running latest git version on Ubuntu 22.04, when trying to add user, after pasting the captcha code I get the error:
ERROR: Can't find the workflow ID in the login form. The page format might have changed.

Is it possible they changed the page format again within a week?

**Comment by otrdriver** [comment]
Running latest version on MacOS Big Sur 11.6.5.
I experienced the same error as dingo35.
Alas I am unable to confirm whether or not it was working previously (a week or more ago) as I just now installed kobo-book-downloader.

**Comment by subdavis** [comment]
My fork uses a different match pattern and is currently working: https://github.com/subdavis/kobo-book-downloader

If anyone wants to fix it here, the working pattern is https://github.com/subdavis/kobo-book-downloader/blob/main/kobodl/kobo.py#L152

**Comment by TnS-hun** [comment]
It would be interesting to know how the login form field looks when the workflow ID cannot be found. Anyway I've changed the code to grab it from a link in the page (similarly to what subdavis has posted).

Sorry for the delay.
