### ISSUE TITLE
captcha response is now 3143 characters long and cannot be pasted entirely

### ISSUE THREAD

**Issue by gdemontalivet** [TnS-hun/kobo-book-downloader#21]
Hi, I tried this today but the captain response is much longer than on your small video, it doesn't seem to work anymore as when pasting it in command line, it doesn't paste more than the 1024 first chatacters

**Comment by TnS-hun** [comment]
What operating system are you using?

I just tried it under Linux and Windows 10 and both works. The captcha was 2990 characters for me.

**Comment by gdemontalivet** [comment]
Hi! I am in macOS

**Comment by TnS-hun** [comment]
I can't test it on macOS but I made a change that likely fixes the issue. Please update the code and try it.

**Comment by gdemontalivet** [comment]
thank you so much!
