### ISSUE TITLE
Cannot log into Kobo Account

### ISSUE THREAD

**Issue by chrisdma** [TnS-hun/kobo-book-downloader#24]
Hello,

I am getting an error message "ERROR: The request has timed out." when trying to log in after pasting in the captcha code. Can this possibly be fixed? 

Thanks,
Chris

![ShareX-Image](https://sharex.host/L1RZtit1bi.png?key=dlyG26aLk3hR3X)

**Comment by TnS-hun** [comment]
Have you tried it again since then? I couldn't reproduce the issue, I could log in without any problems.
