### ISSUE TITLE
I am using the KBD in Termux on Android & using Eruda DevTools: I am stumped as I have a visual Captcha, not a text-based one

### ISSUE THREAD

**Issue by b9Joker108** [TnS-hun/kobo-book-downloader#26]
Thank you so much for this project.

I am using the KBD in Termux on Android & using Eruda DevTools by launching a server through Termux:

```zsh
npx http-server /data/data/com.termux/files/home/kobo-book-downloader/kobo-book-downloader -p 8080
```

Then using the Chrome Android app in incognito, for both the Kobo login site and also for Eruda DevTools, where I inject the JavaScript codelet as instructed and execute.

I am stumped as sometimes I get a Captcha and sometimes I don't. But, when I do get a Captcha, is it a visual problem, not a text-based solution. So, I have nothing to enter in the Termux shell at the request for the Captcha text solution.

Any assistance would be greatly appreciated.

**Comment by TnS-hun** [comment]
Once you solve the captcha two messages will appear in the Developer Console. The first one is "Captcha response:", and the next one is what you need to copy to kobo-book-downloader.

For me it looks like this:
```
Captcha response:
P1_and_a_lot_more_random_characters_after_that.
```
