### ISSUE TITLE
ERROR: Can't find the workflow ID in the login form. The page format might have changed.

### ISSUE THREAD

**Issue by fturco** [TnS-hun/kobo-book-downloader#3]
I get the following error message when running the `python kobo-book-downloader list --all` command:

    ERROR: Can't find the workflow ID in the login form. The page format might have changed.

This is after having inserted username/password/captcha.

I'm using the latest git version of `kobo-book-downloader` on a Gentoo Linux system.

**Comment by TnS-hun** [comment]
I've changed the detection code a bit. Can you please check the latest version?

**Comment by fturco** [comment]
With the latest version I'm now able to download my book from Kobo. Thank you!
