### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by fturco** [TnS-hun/kobo-book-downloader#5]
I'm a GNU/Linux user and I prefer to avoid running proprietary applications. Before discovering `kobo-book-downloader` I was forced to download e-books with Adobe Digital Editions, which is proprietary software. I had to use either Wine or a Windows 10 QEMU guest. Thanks to your program I can now download Kobo books quickly and easily.

Do you accept donations? Do you accept cryptocurrencies like Bitcoin? I would be glad to be the first to donate...

**Comment by TnS-hun** [comment]
This is very of kind of you but it's really not necessary. :smile:
