### ISSUE TITLE
Strip escape sequences when redirecting output to a file

### ISSUE THREAD

**Issue by fturco** [TnS-hun/kobo-book-downloader#8]
I'd like to save my Kobo wishlist locally in a text file, for backup purposes.

I tried with:

    python kobo-book-downloader wishlist > kobo-wishlist.txt

But if I open `kobo-wishlist.txt` with a text editor (emacs) I get the following output:

```
^[[1m1984^[[0m by George Orwell (ISBN: 9780547249643)
^[[1m2001: A Space Odyssey^[[0m by Arthur C. Clarke (ISBN: 9780748120789)
...
```

I could easily remove those escape sequences manually with a simple find & replace, but I wonder if `kobo-book-downloader` can detect if its output is being redirected to a file and, in that case, strip any escape sequence automatically.

What do you think?

**Comment by fturco** [comment]
I just found a nice program called `ansifilter`. Basically I can fix my problem with the following command:

    python kobo-book-downloader wishlist | ansifilter > kobo-wishlist.txt

I could even keep escape sequences and generate an HTML document instead:

    python kobo-book-downloader wishlist | ansifilter --html > kobo-wishlist.html

**Comment by TnS-hun** [comment]
There was a missing call and that's why those sequences were not stripped.

**Comment by fturco** [comment]
I confirm that kobo-book-downloader now strips escape sequences correctly without the need of external programs like ansifilter.

Thank you!
